AWSTemplateFormatVersion: '2010-09-09'
Description: Invoice Textract - Start Analysis Lambda (per-environment)

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (tst / prd)
    AllowedValues:
      - tst
      - prd
    Default: tst

  CodeBucket:
    Type: String
    Description: "S3 bucket where the Lambda zip is stored"

  CodeKey:
    Type: String
    Description: "S3 key for the Lambda zip"

  InvoiceProcessingBucket:
    Type: String
    Description: Name of the existing S3 bucket for invoice processing
    Default: tst-invoice-input #can it be removed?

Resources:
  # SNS topic: Textract publishes job completion here
  InvoiceTextractCompletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${Environment}-invoice-textract-completed'

  # IAM role: Textract assumes this to publish to SNS topic
  TextractPublishToSnsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-TextractPublishToSnsRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - textract.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${Environment}-TextractPublishToSns'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref InvoiceTextractCompletedTopic

  # Execution role for the lambda 1
  TextractStartAnalysisRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-TextractStartAnalysisRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${Environment}-invoice-textract-start-analysis-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:AbortMultipartUpload
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - textract:StartDocumentAnalysis
                  - textract:StartDocumentTextDetection
                Resource: 
                  - !Sub 'arn:aws:s3:::${InvoiceProcessingBucket}'
                  - !Sub 'arn:aws:s3:::${InvoiceProcessingBucket}/pipeline/input/*'


  # Lambda #1: Starts Textract analysis when new files arrive
  InvoiceTextractStartAnalysisFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-invoice-textract-start-analysis"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt TextractStartAnalysisRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
      Runtime: python3.10
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          ENV: !Ref Environment
          SNS_TOPIC_ARN: !Ref InvoiceTextractCompletedTopic
          TEXTRACT_ROLE_ARN: !GetAtt TextractPublishToSnsRole.Arn
      Tags:
        - Key: Project
          Value: "BI Invoice Processing"
        - Key: Owner
          Value: "Business Intelligence"
        - Key: Environment
          Value: !Ref Environment


  # Permission for S3 to call this Lambda
  InvoiceTextractStartAnalysisPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref InvoiceTextractStartAnalysisFunction
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceArn: !Sub 'arn:aws:s3:::${InvoiceProcessingBucket}'


Outputs:
  InvoiceTextractStartAnalysisFunctionName:
    Description: "InvoiceTextractStartAnalysisFunction name"
    Value: !Ref InvoiceTextractStartAnalysisFunction

  InvoiceTextractStartAnalysisFunctionArn:
    Description: "InvoiceTextractStartAnalysisFunction ARN"
    Value: !GetAtt InvoiceTextractStartAnalysisFunction.Arn

  InvoiceTextractCompletedTopicArn:
    Description: "SNS topic ARN for Textract completion"
    Value: !Ref InvoiceTextractCompletedTopic
    Export:
      Name: !Sub "${Environment}-InvoiceTextractCompletedTopicArn"

